### ISSUE TITLE
not an issue but clarification- no caching with eager loading..

### ISSUE THREAD

**Issue by shez1983** [AuthentikCanada/eloquent-cache#1]
so with this package caching only works if you call the model directly and not when eager loading - i think this is a very big disadvantage/draw back... its like having half-baked package as normally you also eagerload stuff.. so i feel this should work (ie your package should cache) unless there was some complicated reason why this couldnt work?

**Comment by rundef** [comment]
Hi,

Bear in mind that this package is quite new ; so models with eagerloading are not cached for the sake of simplicity.
But you are absolutely right, they should be cached and I don't see any reason why that couldn't work.
I'll add that feature in a couple of days.

Thanks !

**Comment by rundef** [comment]
Ok, models with eagerloading are now cached in v**1.1.1**
