### ISSUE TITLE
Laravel 9

### ISSUE THREAD

**Issue by njanik** [AuthentikCanada/eloquent-cache#6]
Good morning Sir,

Any plan to update for laravel 9 please ?

**Comment by spekulatius** [comment]
Hello @njanik and @rundef,

I guess I'm not alone :D I'd love to see a Laravel 9 version too. Have you checked the effort @njanik ?

Cheers,
Peter

**Comment by peterk-mtl** [comment]
Should by fixed with the 1.3.0 [release](https://github.com/AuthentikCanada/eloquent-cache/releases/tag/1.3.0)
